(function(){
if(typeof S==="undefined")return;
const VER="cargro-network-lite-v1",TODAY="2026-06-26",KM={"L3":0.25,"L4":0.35,"Bakwagen":0.45,"Bakwagen laadklep":0.50};
const eur=v=>new Intl.NumberFormat("nl-NL",{style:"currency",currency:"EUR"}).format(Number(v)||0);
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");
const cls=s=>String(s||"").toLowerCase().replace(/[^a-z0-9]+/g,"-");
const badge=s=>`<span class="status ${cls(s)}">${esc(s)}</span>`;
const pill=(s,c="blue")=>`<span class="pill ${c}">${esc(s)}</span>`;
const tbl=(h,rows,empty="Geen data")=>rows.length?`<div class="table-wrap"><table><thead><tr>${h.map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`:`<div class="empty">${empty}</div>`;
const head=(t,p,a="")=>`<section class="page-header"><div><div class="eyebrow">Cargro Private Charter Network</div><h1>${t}</h1><p>${p}</p></div>${a?`<div class="page-actions">${a}</div>`:""}</section>`;
const rt=row=>{let r=R(row),d=(S.routeDetails&&S.routeDetails[r.id])||{};r.rate=Number(d.rate||KM[r.veh]||0.35);r.pay=Number(r.pay)||Math.round((Number(r.km)||0)*r.rate*100)/100;r.revenue=r.pay+(Number(r.margin)||0);r.remarks=d.remarks||"";r.specs=d.specs||"";return r};
const routes=()=>S.routes.map(rt), by=id=>rt(S.routes.find(x=>x[0]===id));
function apps(){return[...(S.routeRequests||[]).map(x=>({kind:"Aanvraag",src:"request",id:x[0],route:x[1],charter:x[2],amount:x[4],status:x[5],note:x[6]})),...(S.bids||[]).map(x=>({kind:"Hoger bod",src:"bid",id:x[0],route:x[1],charter:x[2],amount:x[3],status:x[4],note:x[5]}))]}
function seed(){S.routeTemplates=[["Oost dagroute","Oost","Bakwagen",0.45],["Randstad kleinpakket","Randstad","L4",0.35],["Laadklep zwaar","Noord","Bakwagen laadklep",0.50]];S.capacity={"LuxeLine Transport":[2,2,1,2,1,0,0],"Duiven Express":[1,1,1,0,1,0,0],"Randstad Koeriers":[3,2,2,3,2,1,0],"Noord Carrier Network":[1,1,1,1,1,0,0],"Zuid Logistics Partner":[1,0,1,1,0,0,0]};S.routeThreads=S.routeThreads||{};routes().forEach(r=>S.routeThreads[r.id]=S.routeThreads[r.id]||[[TODAY,"Planning","Route gepubliceerd"],[TODAY,"System","Zichtbaar in private marketplace"]]);S._businessVer=VER;save()}
if(S._businessVer!==VER)seed();
function score(name,r){let c=(S.charters||[]).find(x=>x[0]===name)||[],s=50;if(String(c[10]||"").includes(r.zone))s+=18;if(String(c[3]||"").toLowerCase().includes("complete"))s+=12;if(Number(c[4])>=4.6)s+=10;if((S.capacity[name]||[]).some(x=>x>0))s+=8;if(r.veh.includes("laadklep")&&!S.vehicles.some(v=>v[1]===name&&String(v[2]).includes("laadklep")))s-=22;return Math.max(0,Math.min(99,s))}
function why(name,r){let c=(S.charters||[]).find(x=>x[0]===name)||[],a=[];if(String(c[10]||"").includes(r.zone))a.push("zone-fit");if(String(c[3]||"").toLowerCase().includes("complete"))a.push("docs ok");if(Number(c[4])>=4.6)a.push("reliable");if((S.capacity[name]||[]).some(x=>x>0))a.push("capacity");return a.join(" · ")||"manual review"}
function counts(){return{open:S.routes.filter(r=>r[9]==="open").length,apps:apps().filter(a=>["pending","review"].includes(a.status)).length,assigned:S.routes.filter(r=>r[9]==="assigned").length,inv:S.invoices.filter(i=>["pending","mismatch","review"].includes(i[5])).length,dis:S.disputes.filter(d=>!["Closed","Rejected","closed","rejected"].includes(d[5])).length}}
nav=function(){let c=counts(),office=[["dashboard","Command center",""],["import","Route import",""],["market","Private marketplace","open"],["routeDesk","Route desk","apps"],["settlement","Settlements","inv"],["disputes","Disputes","dis"],["capacity","Capacity",""],["fleet","Fleet & drivers",""],["margin","Marge",""]],charter=[["dashboard","Dashboard",""],["market","Marketplace","open"],["myRoutes","Mijn routes",""],["myApplications","Aanvragen & biedingen",""],["settlement","Settlement",""],["disputes","Disputes","dis"],["capacity","Mijn capaciteit",""],["fleet","Voertuigen & chauffeurs",""]],items=S.role==="office"?office:charter;return`<aside class="sidebar enterprise-sidebar"><div class="sidebar-brand"><div class="logo">CG</div><div><strong>Cargro</strong><span>Private Charter Network</span></div></div><button class="btn ghost full" data-logout>Andere login</button>${S.role==="charter"?`<div class="field compact"><label>Charter</label><select id="charter">${S.charters.map(x=>`<option ${x[0]===S.charter?"selected":""}>${x[0]}</option>`).join("")}</select><small>Bekijk als charter</small></div>`:""}<div class="nav-group-title">Core workflow</div>${items.map(i=>`<button class="nav-btn ${S.view===i[0]?"active":""}" data-view="${i[0]}"><span class="nav-left"><span class="nav-dot"></span>${i[1]}</span>${i[2]&&c[i[2]]?`<span class="badge-count">${c[i[2]]}</span>`:""}</button>`).join("")}<div class="sidebar-note"><strong>Tijdbesparing</strong><span>Aanvragen, hogere biedingen en applicants zitten in één Route Desk.</span></div></aside>`}
function dashboard(){let c=counts(),exp=routes().reduce((a,r)=>a+r.pay,0),sub=S.invoices.reduce((a,i)=>a+Number(i[3]||0),0);return head(S.role==="office"?"Command center":"Charter dashboard",S.role==="office"?"Snel beslissen: wie past op welke route, waarom, voor welk bedrag en met welke settlement impact.":"Je routes, aanvragen, biedingen, settlement en capaciteit in één overzicht.",S.role==="office"?`<button class="btn primary" data-view="routeDesk">Open Route Desk</button>`:`<button class="btn primary" data-view="market">Open marketplace</button>`)+`<div class="network-topline"><div class="command-card"><h3>Beslissingen die tijd besparen</h3><p>Elke route toont applicants, smart score, reden, timeline en financiële impact.</p><div class="decision-grid"><div class="decision-cell"><span>Open routes</span><strong>${c.open}</strong></div><div class="decision-cell"><span>Applicants</span><strong>${c.apps}</strong></div><div class="decision-cell"><span>Assigned</span><strong>${c.assigned}</strong></div><div class="decision-cell"><span>Disputes</span><strong>${c.dis}</strong></div></div></div><div class="command-card"><h3>Financieel</h3><div class="finance-grid"><div class="finance-cell"><span>Expected payout</span><strong>${eur(exp)}</strong></div><div class="finance-cell"><span>Submitted invoices</span><strong>${eur(sub)}</strong></div><div class="finance-cell"><span>Mismatch</span><strong>${eur(S.invoices.reduce((a,i)=>a+Math.abs(Number(i[3]||0)-Number(i[7]||0)),0))}</strong></div><div class="finance-cell"><span>Avg/km</span><strong>${eur(exp/(routes().reduce((a,r)=>a+r.km,0)||1))}</strong></div></div></div></div>${S.role==="office"?routeDesk(true):myApplications(true)}`}
function market(embed=false){let list=routes().filter(r=>r.status==="open"),body=`<div class="private-note">Private marketplace: geen open Trans.eu clone, maar alleen Cargro-approved charters.</div><div class="grid two" style="margin-top:14px">${list.map(routeCard).join("")||`<div class="empty">Geen open routes</div>`}</div>`;return embed?body:head("Private marketplace","Charters vragen routes aan of doen een hoger bod. Office ziet alles gecombineerd in Route Desk.")+body}
function routeCard(r){let req=S.routeRequests.some(x=>x[1]===r.id&&x[2]===S.charter&&x[5]==="pending"),bid=S.bids.some(x=>x[1]===r.id&&x[2]===S.charter&&["pending","review"].includes(x[4])),open=S.expandedSpecs&&S.expandedSpecs[r.id];return`<article class="route-card"><div class="route-top"><div><div class="route-title">${r.title}</div><div class="route-meta">${r.id} · ${r.source} · ${r.zone}</div></div>${badge(r.status)}</div><div class="route-info">${pill(`${r.km} km`,`gray`)}${pill(`${eur(r.rate)}/km`,`blue`)}${pill(`${eur(r.pay)} payout`,`green`)}${pill(`${apps().filter(a=>a.route===r.id).length} applicants`,`orange`)}</div><div class="route-actions"><button class="btn ghost small" data-action="toggleSpecs" data-id="${r.id}">${open?"Verberg":"Specificaties"}</button>${S.role==="charter"?`<button class="btn primary small" data-action="requestRoute" data-id="${r.id}" ${req?"disabled":""}>Aanvragen</button><button class="btn ghost small" data-action="prepareBid" data-id="${r.id}" ${bid?"disabled":""}>Hoger bod</button>`:`<button class="btn primary small" data-view="routeDesk">Applicants</button>`}</div>${open?`<div class="spec-panel"><strong>Opmerking</strong><p>${esc(r.remarks||"Geen")}</p><strong>Specificaties</strong><p>${esc(r.specs||"Geen")}</p></div>`:""}</article>`}
function routeDesk(embed=false){let open=apps().filter(a=>["pending","review"].includes(a.status)),rows=open.map(a=>{let r=by(a.route),sc=score(a.charter,r);return[a.route,r.title,a.charter,a.kind,eur(r.pay),eur(a.amount),`<span class="score-badge ${sc>=80?"good":sc<60?"warn":""}">${sc}</span>`,why(a.charter,r),`<div class="compact-actions"><button class="btn primary small" data-action="assignApplicant" data-id="${a.src}:${a.id}">Assign</button><button class="btn ghost small" data-action="rejectApplicant" data-id="${a.src}:${a.id}">Reject</button></div>`]});let r=open[0]?by(open[0].route):routes()[0],body=`<div class="route-desk-layout"><div>${tbl(["Route","Naam","Charter","Type","System","Requested","Score","Waarom","Actie"],rows,"Geen applicants")}</div><div class="card route-focus"><div class="card-title">Decision summary</div>${r?decision(r):""}</div></div>`;return embed?body:head("Route Desk","Route aanvragen, hogere biedingen en applicants per route zijn gecombineerd. Eén plek om te beslissen.")+body}
function decision(r){let list=apps().filter(a=>a.route===r.id),best=list.slice().sort((a,b)=>score(b.charter,r)-score(a.charter,r))[0];return`<h3>${r.id} · ${r.title}</h3><div class="decision-grid"><div class="decision-cell"><span>System</span><strong>${eur(r.pay)}</strong></div><div class="decision-cell"><span>Applicants</span><strong>${list.length}</strong></div><div class="decision-cell"><span>Best match</span><strong>${best?best.charter:"—"}</strong></div><div class="decision-cell"><span>Score</span><strong>${best?score(best.charter,r):"—"}</strong></div></div><div class="reason-list">${list.map(a=>`<div class="reason-item"><strong>${a.charter} · ${a.kind} · ${eur(a.amount)}</strong><span>${why(a.charter,r)}. Note: ${esc(a.note)}</span></div>`).join("")||`<div class="reason-item"><strong>Geen applicants</strong><span>Route blijft in marketplace.</span></div>`}</div><div class="card-title" style="margin-top:16px">Timeline</div><div class="thread">${(S.routeThreads[r.id]||[]).map(t=>`<div class="thread-item"><time>${t[0]}</time><div><strong>${t[1]}</strong><span>${t[2]}</span></div></div>`).join("")}</div>`}
function myApplications(embed=false){let rows=apps().filter(a=>a.charter===S.charter).map(a=>{let r=by(a.route);return[a.id,a.route,r.title,a.kind,eur(r.pay),eur(a.amount),badge(a.status),esc(a.note)]}),body=tbl(["ID","Route","Naam","Type","System","Requested","Status","Note"],rows,"Geen aanvragen of biedingen");return embed?body:head("Mijn aanvragen & biedingen","Normale aanvragen en hogere biedingen staan gecombineerd.")+body}
function settlement(){let names=S.role==="office"?S.charters.map(c=>c[0]):[S.charter],rows=names.map(ch=>{let rs=routes().filter(r=>r.charter===ch),exp=rs.reduce((a,r)=>a+r.pay,0),sub=S.invoices.filter(i=>i[1]===ch).reduce((a,i)=>a+Number(i[3]||0),0),dis=S.disputes.filter(d=>d[2]===ch&&!["Closed","Rejected"].includes(d[5])).reduce((a,d)=>a+Number(d[7]||0),0);return[ch,rs.length,eur(exp),eur(sub),eur(sub-exp),eur(dis),sub-exp||dis?badge("review"):badge("ready")]});return head("Settlement","Routes, expected payout, invoices, difference en disputes per charter.")+tbl(["Charter","Routes","Expected","Submitted","Difference","Dispute exposure","Status"],rows)}
function capacity(){let days=["Ma","Di","Wo","Do","Vr","Za","Zo"],names=S.role==="office"?S.charters.map(c=>c[0]):[S.charter];return head("Capacity calendar","Planning ziet capaciteit voordat een route wordt toegewezen.")+names.map(name=>`<div class="card" style="margin-bottom:14px"><div class="card-title">${name}</div><div class="capacity-grid">${days.map((d,i)=>`<div class="capacity-day"><strong>${d}</strong><span>${(S.capacity[name]||[])[i]||0}</span><small>voertuigen</small></div>`).join("")}</div>${S.role==="charter"?`<div class="route-actions"><input class="input" name="capacity" placeholder="Bijv. 2,2,1,2,1,0,0"><button class="btn primary small" data-action="saveCapacity">Opslaan</button></div>`:""}</div>`).join("")}
function importPage(){return head("Route import","Templates en mapping besparen planning tijd. Upload routes via bestaande CSV flow of gebruik templates als vaste routeprofielen.")+`<div class="grid two"><div class="card"><div class="card-title">Route templates</div><div class="template-grid">${S.routeTemplates.map((t,i)=>`<div class="template-card"><strong>${t[0]}</strong><span>${t[1]} · ${t[2]} · ${eur(t[3])}/km</span><button class="btn ghost small" data-action="useTemplate" data-id="${i}">Gebruik</button></div>`).join("")}</div></div><div class="card"><div class="card-title">Column mapping</div><p class="muted">MendriX/Excel kolommen eenmalig koppelen: Afstand → KM, voertuig → voertuigtype, laadvenster → laadtijd.</p></div></div>`+market(true)}
function disputes(){let list=S.role==="office"?S.disputes:S.disputes.filter(d=>d[2]===S.charter);return head("Dispute control","Elke dispute heeft status, beslissing en timeline-link naar settlement.")+tbl(["Dispute","Route","Charter","Categorie","Correctie","Status","Beslissing","Actie"],list.map(d=>[d[0],d[1],d[2],d[3],eur(d[7]),badge(d[5]),esc(d[8]),S.role==="office"?`<div class="compact-actions"><button class="btn ghost small" data-action="evidenceDispute" data-id="${d[0]}">Evidence</button><button class="btn primary small" data-action="approveDispute" data-id="${d[0]}">Approve</button><button class="btn ghost small" data-action="partialDispute" data-id="${d[0]}">Partial</button><button class="btn ghost small" data-action="rejectDispute" data-id="${d[0]}">Reject</button></div>`:`<button class="btn ghost small" data-action="replyDispute" data-id="${d[0]}">Reply</button>`]))}
function simpleFleet(){return head("Fleet & drivers","Alleen de data die planning nodig heeft: voertuigtype, chauffeur, status en capaciteit.")+`<div class="grid two"><div>${tbl(["Vehicle","Charter","Type","Plate","Status"],S.vehicles.map(v=>[v[0],v[1],v[2],v[3],badge(v[5])]))}</div><div>${tbl(["Driver","Charter","Name","Phone","Status"],S.drivers.map(d=>[d[0],d[1],d[2],d[3],badge(d[5])]))}</div></div>`}
function margin(){return head("Marge","Intern gekoppeld aan route en gekozen charter.")+tbl(["Route","Charter","Revenue","Payout","Margin","Status"],routes().map(r=>[r.id,r.charter||"—",eur(r.revenue),eur(r.pay),eur(r.margin),badge(r.status)]))}
function renderView(){if(S.role==="office")return({dashboard,import:importPage,market,routeDesk,settlement,disputes,capacity,fleet:simpleFleet,margin}[S.view]||dashboard)();return({dashboard,market,myRoutes:()=>head("Mijn routes","Toegewezen routes.")+tbl(["Route","Naam","KM","Payout","Status"],routes().filter(r=>r.charter===S.charter).map(r=>[r.id,r.title,r.km,eur(r.pay),badge(r.status)])),myApplications,settlement,disputes,capacity,fleet:simpleFleet}[S.view]||dashboard)()}
render=function(){if(!S.loggedIn&&typeof loginScreen==="function"){A.innerHTML=loginScreen();bind();return}A.innerHTML=`<div class="app-shell enterprise">${nav()}<main class="main"><div class="topbar"><div class="kicker">${S.role==="office"?"Cargro Office / Planning":esc(S.charter)}</div><div class="demo-note">Private network prototype</div></div>${renderView()}</main></div>`;bind()};
bind=function(){document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{S.view=b.dataset.view;save();render()});document.querySelectorAll("[data-login]").forEach(b=>b.onclick=()=>{S.role=b.dataset.login;S.loggedIn=true;S.view="dashboard";let c=document.querySelector('[name="loginCharter"]');if(c)S.charter=c.value;save();render()});let lo=document.querySelector("[data-logout]");if(lo)lo.onclick=()=>{S.loggedIn=false;save();render()};let cs=document.getElementById("charter");if(cs)cs.onchange=e=>{S.charter=e.target.value;S.view="dashboard";save();render()};document.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>act(b.dataset.action,b.dataset.id))};
function act(a,id){if(a==="toggleSpecs"){S.expandedSpecs[id]=!S.expandedSpecs[id];save();render();return}if(a==="requestRoute"){let r=by(id);S.routeRequests.unshift([`REQ-${400+S.routeRequests.length}`,id,S.charter,"current",r.pay,"pending","Aanvraag vanuit marketplace",TODAY]);S.routeThreads[id]=(S.routeThreads[id]||[]).concat([[TODAY,S.charter,"Aanvraag tegen prijs ingediend"]]);save();toast("Aanvraag toegevoegd aan Route Desk");render();return}if(a==="prepareBid"){let r=by(id),amount=Math.round(r.pay*1.08);S.bids.unshift([`BID-${500+S.bids.length}`,id,S.charter,amount,"pending",`Hoger bod: ${eur(amount)}`,"higher",TODAY]);S.routeThreads[id]=(S.routeThreads[id]||[]).concat([[TODAY,S.charter,"Hoger bod ingediend"]]);save();toast("Hoger bod toegevoegd aan Route Desk");render();return}if(a==="assignApplicant"){let [src,appId]=id.split(":"),app=src==="bid"?S.bids.find(x=>x[0]===appId):S.routeRequests.find(x=>x[0]===appId);if(!app)return;let routeId=app[1],charter=app[2],amount=src==="bid"?app[3]:app[4],rr=S.routes.find(x=>x[0]===routeId);rr[9]="assigned";rr[13]=charter;rr[11]=amount;S.routeRequests.filter(x=>x[1]===routeId).forEach(x=>x[5]=(src==="request"&&x[0]===appId)?"approved":"rejected");S.bids.filter(x=>x[1]===routeId).forEach(x=>x[4]=(src==="bid"&&x[0]===appId)?"approved":"rejected");S.routeThreads[routeId]=(S.routeThreads[routeId]||[]).concat([[TODAY,"Planning",`Assigned aan ${charter}. Andere applicants afgewezen.`]]);save();toast("Route assigned met beslissing/timeline");render();return}if(a==="rejectApplicant"){let [src,appId]=id.split(":"),app=src==="bid"?S.bids.find(x=>x[0]===appId):S.routeRequests.find(x=>x[0]===appId);if(app){if(src==="bid")app[4]="rejected";else app[5]="rejected";save();toast("Applicant rejected");render()}return}if(["evidenceDispute","approveDispute","partialDispute","rejectDispute","replyDispute"].includes(a)){let d=S.disputes.find(x=>x[0]===id);if(!d)return;let map={evidenceDispute:["Evidence requested","Office vraagt extra bewijs"],approveDispute:["Correction approved","Correctie gaat naar settlement"],partialDispute:["Partially approved","Gedeeltelijk goedgekeurd"],rejectDispute:["Rejected","Dispute afgewezen"],replyDispute:["Under review","Charter reply toegevoegd"]};d[5]=map[a][0];d[8]=map[a][1];d[9]=d[9]||[];d[9].push([TODAY,S.role==="office"?"Office":S.charter,map[a][1]]);save();toast(map[a][1]);render();return}if(a==="saveCapacity"){let inp=document.querySelector('[name="capacity"]');if(inp&&inp.value){S.capacity[S.charter]=inp.value.split(",").map(x=>Number(x.trim())||0).slice(0,7);save();toast("Capaciteit opgeslagen");render()}}}
render();
})();
